models:
  # Example: OpenAI model
  # - name: gpt-4
  #   display_name: GPT-4
  #   use: langchain_openai:ChatOpenAI
  #   model: gpt-4
  #   api_key: $OPENAI_API_KEY # Use environment variable
  #   max_tokens: 4096
  #   temperature: 0.7
  #   supports_vision: true # Enable vision support for view_image tool

  # Example: Anthropic Claude model
  - name: qwen3.5-plus
    display_name: Qwen 3.5 Plus
    use: langchain_anthropic:ChatAnthropic
    model: qwen3.5-plus
    base_url: https://coding.dashscope.aliyuncs.com/apps/anthropic
    api_key: $ANTHROPIC_API_KEY
    # max_tokens: 8192
    supports_vision: true # Enable vision support for view_image tool
    supports_thinking: true
    when_thinking_enabled:
      thinking:
        type: enabled
